<?php

//$_RETORNA_ID['rtid'];

include_once ("../classes/conexoes/conexao.php");

$id = filter_input(INPUT_GET, 'id', FILTER_SANITIZE_NUMBER_INT);
$result_report = "SELECT * FROM `reports` WHERE id = '$id'";
$resultado_report = mysqli_query($conn, $result_report);
$row_report = mysqli_fetch_assoc($resultado_report);

$techi_id = $row_report['techid'];
$result_user = "SELECT * FROM `user` WHERE user_id = '$techi_id'";
$resultado_user = mysqli_query($conn, $result_user);
$row_user = mysqli_fetch_assoc($resultado_user);

$customer_id = $row_report['customer_id'];
$result_customer = "SELECT * FROM `customer` WHERE customer_id = '$customer_id'";
$resultado_customer = mysqli_query($conn, $result_customer);
$row_customer = mysqli_fetch_assoc($resultado_customer);

$dataMesurement = new DateTime($row_report['dtcalibration']);
$dataDue = new DateTime($row_report['dtdue']);

$stdCertDate = new DateTime($row_report['stdcertdate']);
$stdCertDue = new DateTime($row_report['stdcertdue']);

$stdCertDate2 = new DateTime($row_report['stdcertdate2']);
$stdCertDue2 = new DateTime($row_report['stdcertdue2']);

$leiaute = $row_report['stdcertdate2'];
$nome1 = $row_report['id'];
$nome2 = $row_report['customer_id'];
$nome3 = date("Ymd");

if (!empty($leiaute)) {
$html = '';
$html .= '<DOCTYPE html>';
$html .= '<html>';
$html .= '<head>';
$html .= '<meta charset="UTF-8">';
$html .= '<link rel="stylesheet" href="../classes/css/certificado.css"/>';
$html .= '<title>Calibration Report</title>';
$html .= '</head>';
$html .= '<body>';
$html .= '<div class="pai">';
$html .= '<p> <b><u>Top Scale, Inc. Calibration Report</u></b> <br>';
$html .= 'P.O. Box 7542 <br> ';
$html .= 'Riverside, CA  92513 <br>';
$html .= '(951)785-1700 <br>';
$html .= '<b>ISO 9001/2015</b> <br>';
$html .= '<b>PAGE <u>1</u> OF <u>1</u></b></p>';
$html .= '<br>';
$html .= '<table class="tg">';
$html .= '<thead>';
$html .= '<tr>';
$html .= '<th class="tg-6hwh" colspan="3"><b>'  . $row_customer['customer_name'] . "</b></th>";
$html .= '<th class="tg-6hwh"></th>';
$html .= '<th class="tg-6hwh"></th>';
$html .= '<th class="tg-6hwh"></th>';
$html .= '<th class="tg-6hwh"></th>';
$html .= '<th class="tg-6hwh"></th>';
$html .= '<th class="tg-6hwh"></th>';
$html .= '<th class="tg-6hwh" colspan="2"><b>DATE:&nbsp;&nbsp;&nbsp;'  . $dataMesurement -> format('m/d/Y') . "</b></th>";
$html .= '</tr>';
$html .= '</thead>';
$html .= '</table>';
$html .= '<div>';
$html .= '<table class="tg">';
$html .= '<thead>';
$html .= '<tr>';
$html .= '<th class="tg-1woa" colspan="2">location</th>';
$html .= '<th class="tg-1woa">Control#</th>';
$html .= '<th class="tg-1woa">Mfgr.</th>';
$html .= '<th class="tg-1woa">Model</th>';
$html .= '<th class="tg-1woa">S/N</th>';
$html .= '<th class="tg-1woa" colspan="2">Type</th>';
$html .= '<th class="tg-1woa" colspan="2">Capacity</th>';
$html .= '</tr>';
$html .= '</thead>';
$html .= '<tbody>';
$html .= '<tr>';
$html .= '<td class="tg-6hxq" colspan="2">' . $row_report['location'] . "</td>";
$html .= '<td class="tg-6hxq">' . $row_report['control'] . "</td>";
$html .= '<td class="tg-6hxq">' . $row_report['manufacturer'] . "</td>";
$html .= '<td class="tg-6hxq">' . $row_report['model'] . "</td>";
$html .= '<td class="tg-6hxq">' . $row_report['sn'] . "</td>";
$html .= '<td class="tg-6hxq" colspan="2">' . $row_report['type'] . "</td>";
$html .= '<td class="tg-6hxq" colspan="2">' . $row_report['capacity'] . "</td>";
$html .= '</tr>';
$html .= '<tr>';
$html .= '<td class="tg-6hwh"></td>';
$html .= '<td class="tg-6hwh"></td>';
$html .= '<td class="tg-1woa" colspan="6">Pre-Inspection Test Results</td>';
$html .= '<td class="tg-6hwh"></td>';
$html .= '<td class="tg-6hwh"></td>';
$html .= '</tr>';
$html .= '</tbody>';
$html .= '</table>';
$html .= '<table class="tg">';
$html .= '<thead>';
$html .= '<tr>';
$html .= '<th class="tg-6hxq">Wt</th>';
$html .= '<th class="tg-6hxq">&nbsp;&nbsp;&nbsp;&nbsp;' . $row_report['preweight5'] . "&nbsp;&nbsp;&nbsp;&nbsp;</th>";
$html .= '<th class="tg-6hxq">Wt:</th>';
$html .= '<th class="tg-6hxq">' . $row_report['preweight4'] . "</th>";
$html .= '<th class="tg-6hxq">Wt:</th>';
$html .= '<th class="tg-6hxq">' . $row_report['preweight3'] . "</th>";
$html .= '<th class="tg-6hxq">Wt:</th>';
$html .= '<th class="tg-6hxq">' . $row_report['preweight2'] . "</th>";
$html .= '<th class="tg-6hxq">Wt:</th>';
$html .= '<th class="tg-6hxq">' . $row_report['preweight1'] . "</th>";
$html .= '</tr>';
$html .= '</thead>';
$html .= '<tbody>';
$html .= '<tr>';
$html .= '<td class="tg-6hxq">Error</td>';
$html .= '<td class="tg-6hxq">&nbsp;&nbsp;' . $row_report['preerror5'] . "&nbsp;&nbsp;</td>";
$html .= '<td class="tg-6hxq">Error</td>';
$html .= '<td class="tg-6hxq">' . $row_report['preerror4'] . "</td>";
$html .= '<td class="tg-6hxq">Error:</td>';
$html .= '<td class="tg-6hxq">' . $row_report['preerror3'] . "</td>";
$html .= '<td class="tg-6hxq">Error:</td>';
$html .= '<td class="tg-6hxq">' . $row_report['preerror2'] . "</td>";
$html .= '<td class="tg-6hxq">Error:</td>';
$html .= '<td class="tg-6hxq">' . $row_report['preerror1'] . "</td>";
$html .= '</tr>';
$html .= '<tr>';
$html .= '<td class="tg-6hwh"></td>';
$html .= '<td class="tg-6hwh"></td>';
$html .= '<td class="tg-1woa" colspan="6">Test Results After Adjustments</td>';
$html .= '<td class="tg-6hwh"></td>';
$html .= '<td class="tg-6hwh"></td>';
$html .= '</tr>';
$html .= '</tbody>';
$html .= '</table>';
$html .= '<table class="tg">';
$html .= '<thead>';
$html .= '<tr>';
$html .= '<th class="tg-6hxq">Wt</th>';
$html .= '<th class="tg-6hxq">' . $row_report['afterweight5'] . "</th>";
$html .= '<th class="tg-6hxq">Wt:</th>';
$html .= '<th class="tg-6hxq">' . $row_report['afterweight4'] . "</th>";
$html .= '<th class="tg-6hxq">Wt:</th>';
$html .= '<th class="tg-6hxq">' . $row_report['afterweight3'] . "</th>";
$html .= '<th class="tg-6hxq">Wt:</th>';
$html .= '<th class="tg-6hxq">' . $row_report['afterweight2'] . "</th>";
$html .= '<th class="tg-6hxq">Wt:</th>';
$html .= '<th class="tg-6hxq">' . $row_report['afterweight1'] . "</th>";
$html .= '</tr>';
$html .= '</thead>';
$html .= '<tbody>';
$html .= '<tr>';
$html .= '<td class="tg-6hxq">Error</td>';
$html .= '<td class="tg-6hxq">&nbsp;&nbsp;' . $row_report['aftererror5'] . "&nbsp;&nbsp;</td>";
$html .= '<td class="tg-6hxq">Error</td>';
$html .= '<td class="tg-6hxq">' . $row_report['aftererror4'] . "</td>";
$html .= '<td class="tg-6hxq">Error:</td>';
$html .= '<td class="tg-6hxq">' . $row_report['aftererror3'] . "</td>";
$html .= '<td class="tg-6hxq">Error:</td>';
$html .= '<td class="tg-6hxq">' . $row_report['aftererror2'] . "</td>";
$html .= '<td class="tg-6hxq">Error:</td>';
$html .= '<td class="tg-6hxq">' . $row_report['aftererror1'] . "</td>";
$html .= '</tr>';
$html .= '</tbody>';
$html .= '</table>';
$html .= '<table class="tg">';
$html .= '<tbody>';
$html .= '<tr>';
$html .= '<td class="tg-6hwc">Comments: ' . $row_report['comment'] . "</td>";
$html .= '</tr>';
$html .= '</tbody>';
$html .= '</table>';
$html .= '<table class="tg">';
$html .= '<thead>';
$html .= '<tr>';
$html .= '<th class="tg-1woa" colspan="2">Cal Date</th>';
$html .= '<th class="tg-1woa">Cal Due</th>';
$html .= '<th class="tg-1woa">Tech ID#</th>';
$html .= '<th class="tg-1woa">NIST ID#</th>';
$html .= '<th class="tg-1woa">Std Cert#</th>';
$html .= '<th class="tg-1woa" colspan="2">Std Cert. Date</th>';
$html .= '<th class="tg-1woa" colspan="2">Std Cert Due</th>';
$html .= '</tr>';
$html .= '</thead>';
$html .= '<tbody>';
$html .= '<tr>';



$html .= '<td class="tg-6hxq" colspan="2">' . $dataMesurement -> format('m/d/Y') . "</td>";
$html .= '<td class="tg-6hxq">' . $dataDue -> format('m/Y') . "</td>";
$html .= '<td class="tg-6hxq">' . $row_user['techid'] . "</td>";
$html .= '<td class="tg-6hxq">' . $row_report['nistid'] . "</td>";
$html .= '<td class="tg-6hxq">' . $row_report['stdcert'] . "</td>";
$html .= '<td class="tg-6hxq" colspan="2">' . $stdCertDate -> format('m/Y') . "</td>";
$html .= '<td class="tg-6hxq" colspan="2">' . $stdCertDue -> format('m/Y') . "</td>";
$html .= '</tr>';
$html .= '</tbody>';

$html .= '<tr>';
$html .= '<td class="tg-6hxq" colspan="2">' . $dataMesurement -> format('m/d/Y') . "</td>";
$html .= '<td class="tg-6hxq">' . $dataDue -> format('m/Y') . "</td>";
$html .= '<td class="tg-6hxq">' . $row_user['techid'] . "</td>";
$html .= '<td class="tg-6hxq">' . $row_report['nistid2'] . "</td>";
$html .= '<td class="tg-6hxq">' . $row_report['stdcert2'] . "</td>";
$html .= '<td class="tg-6hxq" colspan="2">' . $stdCertDate2 -> format('m/Y') . "</td>";
$html .= '<td class="tg-6hxq" colspan="2">' . $stdCertDue2 -> format('m/Y') . "</td>";

$html .= '</tr>';
$html .= '</tbody>';

$html .= '</table>';
$html .= '</div>';
$html .= '<div class="rodapeleft">';
$html .= '<p>';
$html .= 'Top Scale, Inc. certifies that the above listed instruments were calibrated to manufacturer’s specifications.  ';
$html .= '<b>Standards are traceable to the National Institute of Standards and Technologies through documents on the ';
$html .= 'file at Top Scale, Inc. Procedures and policies comply with MIL-STD-45662a and ANSI/Z540-1-1998.  ';
$html .= 'All inst.. ±.1% of full capacity.</b>';
$html .= '</p>';
$html .= '<br>';
$html .= '<p><b>';
$html .= 'TECHNICIAN SIGNATURE:  ________________________________________________________';
$html .= '</b></p>';
$html .= '</div>';
$html .= '<div class="rodaperight">';
$html .= '<p>';
$html .= '<b>ISO CERT NO. 2019-R0031</b>';
$html .= '<br>';
$html .= '</p>';
$html .= '</div>';
$html .= '</div>';
$html .= '</body>';
$html .= '</html>';

    } else {
        
$html = '';
$html .= '<DOCTYPE html>';
$html .= '<html>';
$html .= '<head>';
$html .= '<meta charset="UTF-8">';
$html .= '<link rel="stylesheet" href="../classes/css/certificado.css"/>';
$html .= '<title>Calibration Report</title>';
$html .= '</head>';
$html .= '<body>';
$html .= '<div class="pai">';
$html .= '<p> <b><u>Top Scale, Inc. Calibration Report</u></b> <br>';
$html .= 'P.O. Box 7542 <br> ';
$html .= 'Riverside, CA  92513 <br>';
$html .= '(951)785-1700 <br>';
$html .= '<b>ISO 9001/2015</b> <br>';
$html .= '<b>PAGE <u>1</u> OF <u>1</u></b></p>';
$html .= '<br>';
$html .= '<table class="tg">';
$html .= '<thead>';
$html .= '<tr>';
$html .= '<th class="tg-6hwh" colspan="3"><b>'  . $row_customer['customer_name'] . "</b></th>";
$html .= '<th class="tg-6hwh"></th>';
$html .= '<th class="tg-6hwh"></th>';
$html .= '<th class="tg-6hwh"></th>';
$html .= '<th class="tg-6hwh"></th>';
$html .= '<th class="tg-6hwh"></th>';
$html .= '<th class="tg-6hwh"></th>';
$html .= '<th class="tg-6hwh" colspan="2"><b>DATE:&nbsp;&nbsp;&nbsp; '  . $dataMesurement -> format('m/d/Y') . "</b></th>";
$html .= '</tr>';
$html .= '</thead>';
$html .= '</table>';
$html .= '<div>';
$html .= '<table class="tg">';
$html .= '<thead>';
$html .= '<tr>';
$html .= '<th class="tg-1woa" colspan="2">location</th>';
$html .= '<th class="tg-1woa">Control#</th>';
$html .= '<th class="tg-1woa">Mfgr.</th>';
$html .= '<th class="tg-1woa">Model</th>';
$html .= '<th class="tg-1woa">S/N</th>';
$html .= '<th class="tg-1woa" colspan="2">Type</th>';
$html .= '<th class="tg-1woa" colspan="2">Capacity</th>';
$html .= '</tr>';
$html .= '</thead>';
$html .= '<tbody>';
$html .= '<tr>';
$html .= '<td class="tg-6hxq" colspan="2">' . $row_report['location'] . "</td>";
$html .= '<td class="tg-6hxq">' . $row_report['control'] . "</td>";
$html .= '<td class="tg-6hxq">' . $row_report['manufacturer'] . "</td>";
$html .= '<td class="tg-6hxq">' . $row_report['model'] . "</td>";
$html .= '<td class="tg-6hxq">' . $row_report['sn'] . "</td>";
$html .= '<td class="tg-6hxq" colspan="2">' . $row_report['type'] . "</td>";
$html .= '<td class="tg-6hxq" colspan="2">' . $row_report['capacity'] . "</td>";
$html .= '</tr>';
$html .= '<tr>';
$html .= '<td class="tg-6hwh"></td>';
$html .= '<td class="tg-6hwh"></td>';
$html .= '<td class="tg-1woa" colspan="6">Pre-Inspection Test Results</td>';
$html .= '<td class="tg-6hwh"></td>';
$html .= '<td class="tg-6hwh"></td>';
$html .= '</tr>';
$html .= '</tbody>';
$html .= '</table>';
$html .= '<table class="tg">';
$html .= '<thead>';
$html .= '<tr>';
$html .= '<th class="tg-6hxq">Wt</th>';
$html .= '<th class="tg-6hxq">&nbsp;&nbsp;&nbsp;&nbsp;' . $row_report['preweight5'] . "&nbsp;&nbsp;&nbsp;&nbsp;</th>";
$html .= '<th class="tg-6hxq">Wt:</th>';
$html .= '<th class="tg-6hxq">' . $row_report['preweight4'] . "</th>";
$html .= '<th class="tg-6hxq">Wt:</th>';
$html .= '<th class="tg-6hxq">' . $row_report['preweight3'] . "</th>";
$html .= '<th class="tg-6hxq">Wt:</th>';
$html .= '<th class="tg-6hxq">' . $row_report['preweight2'] . "</th>";
$html .= '<th class="tg-6hxq">Wt:</th>';
$html .= '<th class="tg-6hxq">' . $row_report['preweight1'] . "</th>";
$html .= '</tr>';
$html .= '</thead>';
$html .= '<tbody>';
$html .= '<tr>';
$html .= '<td class="tg-6hxq">Error</td>';
$html .= '<td class="tg-6hxq">&nbsp;&nbsp;' . $row_report['preerror5'] . "&nbsp;&nbsp;</td>";
$html .= '<td class="tg-6hxq">Error</td>';
$html .= '<td class="tg-6hxq">' . $row_report['preerror4'] . "</td>";
$html .= '<td class="tg-6hxq">Error:</td>';
$html .= '<td class="tg-6hxq">' . $row_report['preerror3'] . "</td>";
$html .= '<td class="tg-6hxq">Error:</td>';
$html .= '<td class="tg-6hxq">' . $row_report['preerror2'] . "</td>";
$html .= '<td class="tg-6hxq">Error:</td>';
$html .= '<td class="tg-6hxq">' . $row_report['preerror1'] . "</td>";
$html .= '</tr>';
$html .= '<tr>';
$html .= '<td class="tg-6hwh"></td>';
$html .= '<td class="tg-6hwh"></td>';
$html .= '<td class="tg-1woa" colspan="6">Test Results After Adjustments</td>';
$html .= '<td class="tg-6hwh"></td>';
$html .= '<td class="tg-6hwh"></td>';
$html .= '</tr>';
$html .= '</tbody>';
$html .= '</table>';
$html .= '<table class="tg">';
$html .= '<thead>';
$html .= '<tr>';
$html .= '<th class="tg-6hxq">Wt</th>';
$html .= '<th class="tg-6hxq">' . $row_report['afterweight5'] . "</th>";
$html .= '<th class="tg-6hxq">Wt:</th>';
$html .= '<th class="tg-6hxq">' . $row_report['afterweight4'] . "</th>";
$html .= '<th class="tg-6hxq">Wt:</th>';
$html .= '<th class="tg-6hxq">' . $row_report['afterweight3'] . "</th>";
$html .= '<th class="tg-6hxq">Wt:</th>';
$html .= '<th class="tg-6hxq">' . $row_report['afterweight2'] . "</th>";
$html .= '<th class="tg-6hxq">Wt:</th>';
$html .= '<th class="tg-6hxq">' . $row_report['afterweight1'] . "</th>";
$html .= '</tr>';
$html .= '</thead>';
$html .= '<tbody>';
$html .= '<tr>';
$html .= '<td class="tg-6hxq">Error</td>';
$html .= '<td class="tg-6hxq">&nbsp;&nbsp;' . $row_report['aftererror5'] . "&nbsp;&nbsp;</td>";
$html .= '<td class="tg-6hxq">Error</td>';
$html .= '<td class="tg-6hxq">' . $row_report['aftererror4'] . "</td>";
$html .= '<td class="tg-6hxq">Error:</td>';
$html .= '<td class="tg-6hxq">' . $row_report['aftererror3'] . "</td>";
$html .= '<td class="tg-6hxq">Error:</td>';
$html .= '<td class="tg-6hxq">' . $row_report['aftererror2'] . "</td>";
$html .= '<td class="tg-6hxq">Error:</td>';
$html .= '<td class="tg-6hxq">' . $row_report['aftererror1'] . "</td>";
$html .= '</tr>';
$html .= '</tbody>';
$html .= '</table>';
$html .= '<table class="tg">';
$html .= '<tbody>';
$html .= '<tr>';
$html .= '<td class="tg-6hwc">Comments: ' . $row_report['comment'] . "</td>";
$html .= '</tr>';
$html .= '</tbody>';
$html .= '</table>';
$html .= '<table class="tg">';
$html .= '<thead>';
$html .= '<tr>';
$html .= '<th class="tg-1woa" colspan="2">Cal Date</th>';
$html .= '<th class="tg-1woa">Cal Due</th>';
$html .= '<th class="tg-1woa">Tech ID#</th>';
$html .= '<th class="tg-1woa">NIST ID#</th>';
$html .= '<th class="tg-1woa">Std Cert#</th>';
$html .= '<th class="tg-1woa" colspan="2">Std Cert. Date</th>';
$html .= '<th class="tg-1woa" colspan="2">Std Cert Due</th>';
$html .= '</tr>';
$html .= '</thead>';
$html .= '<tbody>';
$html .= '<tr>';
$html .= '<td class="tg-6hxq" colspan="2">' . $dataMesurement -> format('m/d/Y') . "</td>";
$html .= '<td class="tg-6hxq">' . $dataDue -> format('m/Y') . "</td>";
$html .= '<td class="tg-6hxq">' . $row_user['techid'] . "</td>";
$html .= '<td class="tg-6hxq">' . $row_report['nistid'] . "</td>";
$html .= '<td class="tg-6hxq">' . $row_report['stdcert'] . "</td>";
$html .= '<td class="tg-6hxq" colspan="2">' . $stdCertDate -> format('m/Y') . "</td>";
$html .= '<td class="tg-6hxq" colspan="2">' . $stdCertDue -> format('m/Y') . "</td>";

$html .= '</tr>';
$html .= '</tbody>';

$html .= '</table>';
$html .= '</div>';
$html .= '<div class="rodapeleft">';
$html .= '<p>';
$html .= 'Top Scale, Inc. certifies that the above listed instruments were calibrated to manufacturer’s specifications.  ';
$html .= '<b>Standards are traceable to the National Institute of Standards and Technologies through documents on the ';
$html .= 'file at Top Scale, Inc. Procedures and policies comply with MIL-STD-45662a and ANSI/Z540-1-1998.  ';
$html .= 'All inst.. ±.1% of full capacity.</b>';
$html .= '</p>';
$html .= '<br>';
$html .= '<p><b>';
$html .= 'TECHNICIAN SIGNATURE:  ________________________________________________________';
$html .= '</b></p>';
$html .= '</div>';
$html .= '<div class="rodaperight">';
$html .= '<p>';
$html .= '<b>ISO CERT NO. 2019-R0031</b>';
$html .= '<br>';
$html .= '</p>';
$html .= '</div>';
$html .= '</div>';
$html .= '</body>';
$html .= '</html>';
        
    } 


use Dompdf\Dompdf;

require_once ("dompdf/autoload.inc.php");

$dompdf = new DOMPDF();

$dompdf->load_html('
' . $html . '
            ');
     $dompdf->render();
     
     //$output = $dompdf->output();
    //file_put_contents("../impressoes/REPORTID" . $nome1 ."CMID". $nome2 ."DT".$nome3.".pdf", $output);
        
     $dompdf->stream(
             "REPORTID" . $nome1 ."CMID". $nome2 ."DT".$nome3.".pdf",
             array(
                 "Attachment"=> false
             )
        );           
    header("Location: ../consultas/consult_calibration_report.php");
?>